<?xml version="1.0"?>
<robot xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#slider"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="caster_offset_length" value="0.53388"/>
    <xacro:property name="caster_offset_height" value="0.10833"/>
    <xacro:property name="caster_trail_height" value="0.12000"/>
    <xacro:property name="caster_trail_length" value="0.01"/>
    <xacro:property name="caster_radius" value="0.102"/>
    <xacro:property name="caster_width"  value="0.075"/>
    <xacro:property name="caster_weight" value="1.225"/>
    <xacro:property name="caster_width" value="0.06"/>

    <xacro:macro name="caster">
        <joint name="caster_pivot_joint" type="continuous">
            <parent link="base_link"/>
            <child link="caster_pivot_link"/>
            <origin xyz="${-caster_offset_length} 0 ${caster_offset_height}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>
        <link name="caster_pivot_link">
            <visual>
                <origin xyz="${caster_radius} -0.055 ${-caster_radius - caster_trail_height}"
                        rpy="${PI/2} 0 ${PI}"/>
                <geometry>
                    <mesh filename="package://navi_model/meshes/caster.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="red"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${EPS} ${EPS} ${EPS}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.01"/>
                <inertia ixx="0.01" ixy="0.000"  ixz="0.000"
                                     iyy="0.01" iyz="0.000"
                                                  izz="0.01"/>
            </inertial>
        </link>
        <gazebo reference="caster_pivot_link">
            <material>Gazebo/Red</material>
        </gazebo>

        <joint name="caster_joint" type="continuous">
            <parent link="caster_pivot_link"/>
            <child link="caster_link"/>
            <origin xyz="${-caster_trail_length} 0 ${-caster_trail_height}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
        <link name="caster_link">
            <inertial>
                <mass value="${caster_weight}"/>
                <inertia ixx="0.100" ixy="0.000" ixz="0.000"
                                     iyy="0.100" iyz="0.000"
                                                 izz="0.100"/>
            </inertial>
            <collision>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
                <geometry>
                    <cylinder radius="${caster_radius}" length="${caster_width}"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
                <geometry>
                    <cylinder radius="${caster_radius}" length="${caster_width}"/>
                </geometry>
                <material name="red"/>
            </visual>
        </link>
        <gazebo reference="caster_link">
            <material>Gazebo/Red</material>
        </gazebo>

        <gazebo reference="caster_link">
            <mu1 value="100.0"/>
            <mu2 value="100.0"/>
            <kp value="1000000.0"/>
            <kd value="1.0"/>
        </gazebo>
    </xacro:macro>
</robot>
