<?xml version="1.0"?>
<robot xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#slider"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="chassis">
        <link name="base_footprint">
            <xacro:weightless/>
        </link>

        <joint name="base_link_joint" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin xyz="0 0 ${wheel_radius}"/>
        </joint>
        <link name="base_link">
            <inertial>
                <mass value="1.0"/>
                <inertia ixx="1.0" ixy="0.0"   ixz="0.0"
                                   iyy="100.0" iyz="0.0"
                                               izz="1.0" />
            </inertial>
            <visual>
                <origin xyz="0 0 ${2*wheel_radius}" rpy="0 0 0"/>
                <geometry>
                    <box size="0.9 0.8 0.3"/>
                    <!--<mesh filename="package://navi_model/meshes/frame.stl" scale="0.001 0.001 0.001"/>-->
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 ${4*wheel_radius}" rpy="0 0 0"/>
                <geometry>
                    <box size="0.9 0.8 0.3"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference="base_link">
            <material>Gazebo/Blue</material>
        </gazebo> 
    </xacro:macro>
</robot>
