<?xml version="1.0"?>
<robot xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#slider"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="robot_width"  value="0.850"/>
    <xacro:property name="robot_length" value="1.350"/>
    <xacro:property name="robot_height" value="0.100"/>
    <xacro:property name="robot_weight" value="90.718"/>

    <link name="base_link">
        <inertial>
            <origin xyz="-0.4 0.0 0.3" rpy="0 0 0"/>
            <mass value="${robot_weight}"/>
            <inertia ixx="1.000" ixy="0.000"  ixz="0.000"
                                 iyy="28.500" iyz="0.000"
                                              izz="34.800"/>
        </inertial>
        <!-- TODO: This bounding box isn't very accurate. -->
        <collision>
            <origin xyz="-0.25 0 ${2*wheel_radius}" rpy="0 0 0"/>
            <geometry>
                <box size="0.83 0.60 0.25"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="-0.6 0.3 0.0" rpy="${PI/2} 0 0"/>
            <geometry>
                <mesh filename="package://navi_model/meshes/frame.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 ${-wheel_radius}" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
        <anchor xyz="0 0 0"/>
    </joint>
    <link name="base_footprint">
        <xacro:weightless/>
    </link>
</robot>
