<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="navi">
	<xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="navi_width" value="0.85"/>
    <xacro:property name="navi_length" value="1.35"/>

    <link name="base_link">
    </link>

    <joint name="base_to_visual" type="fixed">
        <parent link="base_link"/>
        <child link="visual"/>
        <origin xyz="${-navi_length/2} ${navi_width/2} 0" rpy="${PI/2} 0 0"/>
    </joint>
    <link name="visual">
        <visual>
            <geometry>
                <mesh filename="package://navi_model/meshes/navi2.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 1"/>
            </material>
        </visual>
    </link>
</robot>
