<?xml version="1.0"?>
<robot xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#slider"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="offset_width"  value="0.600"/>
    <xacro:property name="offset_height" value="0.127"/>
    <xacro:property name="offset_length" value="0.600"/>
    <link name="base_link">
        <inertial>
            <mass value="${robot_weight}"/>
            <inertia ixx="1.000" ixy="0.000" ixz="0.000"
                                 iyy="1.000" iyz="0.000"
                                             izz="1.000"/>
        </inertial>
        <!-- TODO: This bounding box isn't very accurate. -->
        <collision>
            <origin xyz="0 0 ${robot_height/2+wheel_radius}" rpy="0 0 0"/>
            <geometry>
                <box size="${robot_length/2} ${robot_width} ${robot_height-wheel_radius}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="-${offset_length} ${offset_width/2} -${offset_height}" rpy="${PI/2} 0 0"/>
            <geometry>
                <mesh filename="package://navi_model/meshes/frame.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>
</robot>
