<?xml version="1.0"?>
<robot xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#slider"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:xacro="http://ros.org/wiki/xacro"
       name="navi">
    <xacro:property name="EPS" value="0.000001"/>
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="robot_weight" value="90.0"/>
    <xacro:property name="wheel_radius" value="0.127"/>
    <xacro:property name="wheel_thickness" value="0.150"/>
    <xacro:property name="wheel_separation" value="1.000"/>
    <xacro:property name="robot_clearance" value="0.170"/>
    <xacro:property name="caster_radius" value="0.095"/>
    <xacro:property name="caster_thickness" value="0.064"/>

    <link name="base_link">
        <inertial>
            <origin xyz="0 0 0"/> 
            <mass value="1.0"/>
            <inertia ixx="1.0" ixy="0.0"   ixz="0.0"
                               iyy="100.0" iyz="0.0"
                                           izz="1.0" />
        </inertial>
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="0.9 0.8 0.3"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="0.9 0.8 0.3"/>
            </geometry>
        </collision>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo> 
    <joint name="wheel_left_joint" type="fixed">
        <parent link="base_link"/>
        <child link="wheel_left_link"/>
        <origin xyz="0 ${wheel_separation/2} ${-robot_clearance}" rpy="${PI/2} 0 0"/>
    </joint>
    <link name="wheel_left_link">
        <inertial>
            <origin xyz="0 0 0"/> 
            <mass value="1.0"/>
            <inertia ixx="1.0" ixy="0.0"   ixz="0.0"
                               iyy="100.0" iyz="0.0"
                                           izz="1.0"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
    </link>

    <joint name="wheel_right_joint" type="fixed">
        <parent link="base_link"/>
        <child link="wheel_right_link"/>
        <origin xyz="0 ${-wheel_separation/2} ${-robot_clearance}" rpy="${PI/2} 0 0"/>
    </joint>
    <link name="wheel_right_link">
        <inertial>
            <origin xyz="0 0 0"/> 
            <mass value="1.0"/>
            <inertia ixx="1.0" ixy="0.0"   ixz="0.0"
                               iyy="100.0" iyz="0.0"
                                           izz="1.0" />
        </inertial>
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
    </link>

    <joint name="caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_link"/>
        <origin xyz="-1 0 ${-robot_clearance-(wheel_radius-caster_radius)}"
                rpy="${PI/2} 0 0"/>
    </joint>
    <link name="caster_link">
        <inertial>
            <origin xyz="0 0 0"/> 
            <mass value="1.0"/>
            <inertia ixx="1.0" ixy="0.0"   ixz="0.0"
                               iyy="100.0" iyz="0.0"
                                           izz="1.0" />
        </inertial>
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${caster_radius}" length="${caster_thickness}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${caster_radius}" length="${caster_thickness}"/>
            </geometry>
        </collision>
    </link>
</robot>
