<?xml version="1.0"?>
<robot xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#slider"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="wheel" params="side sign">
        <joint name="wheel_${side}_joint" type="continuous">
            <parent link="base_footprint"/>
            <child link="wheel_${side}_link"/>
            <origin xyz="0 ${sign*wheel_offset} ${wheel_radius}"/>
            <axis xyz="0 1 0"/>
            <anchor xyz="0 0 0"/>
        </joint>
        <link name="wheel_${side}_link">
            <inertial>
                <mass value="${wheel_weight}"/>
                <inertia ixx="0.001" ixy="0.000" ixz="0.000"
                                     iyy="0.001" iyz="0.000"
                                                 izz="0.001"/>
            </inertial>
            <collision>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="red"/>
            </visual>
        </link>
        <transmission type="pr2_mechanism_model/SimpleTransmission" name="wheel_${side}_transmission">
            <actuator name="wheel_${side}_motor"/>
            <joint name="wheel_${side}_joint"/>
            <mechanicalReduction>1.0</mechanicalReduction>
        </transmission>
        <gazebo reference="wheel_${side}_link">
            <material>Gazebo/Red</material>
            <mu1 value="100.0"/>
            <mu2 value="100.0"/>
            <kp value="1000000.0"/>
            <kd value="1.0"/>
        </gazebo>
    </xacro:macro>
</robot>
