<?xml version="1.0"?>
<robot xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#slider"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="wheel" params="side sign">
        <joint name="wheel_${side}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="wheel_${side}_link"/>
            <origin xyz="0 ${0.5*sign*wheel_separation} 0" rpy="${PI/2} 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>
        <link name="wheel_${side}_link">
            <inertial>
                <mass value="${wheel_mass}"/>
                <inertia ixx="${wheel_mass*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
                         iyy="${wheel_mass*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
                         izz="${wheel_mass*wheel_radius*wheel_radius/2}"/>
            </inertial>
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference="wheel_${side}_link">
            <material>Gazebo/Red</material>
        </gazebo> 
    </xacro:macro>

    <xacro:macro name="caster">
        <joint name="caster_pivot_joint" type="continuous">
            <parent link="base_link"/>
            <child link="caster_pivot_link"/>
            <origin xyz="${-caster_separation} 0 ${-caster_clearance)}"
                    rpy="${PI/2} 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
        <link name="caster_pivot_link">
            <inertial>
                <mass value="${caster_mass}"/>
                <inertia ixx="${EPS}" ixy="0"      ixz="0"
                                      iyy="${EPS}" iyz="0"
                                                   izz="${EPS}"/>
            </inertial>
        </link>

        <joint name="caster_joint" type="fixed">
            <parent link="caster_pivot_link"/>
            <child link="caster_link"/>
            <origin xyz="${-caster_offset_axis} ${-caster_offset_height} 0"/>
            <axis xyz="0 0 1"/>
        </joint>
        <link name="caster_link">
            <inertial>
                <mass value="${caster_mass}"/>
                <inertia ixx="${caster_mass*(3*caster_radius*caster_radius + caster_thickness*caster_thickness)}" ixy="0.0" ixz="0.0"
                         iyy="${caster_mass*(3*caster_radius*caster_radius + caster_thickness*caster_thickness)}" iyz="0.0"
                         izz="${caster_mass*caster_radius*caster_radius/2}"/>
            </inertial>
            <visual>
                <inertia ixx="${wheel_mass*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
                         iyy="${wheel_mass*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
                         izz="${wheel_mass*wheel_radius*wheel_radius/2}"/>
                <geometry>
                    <cylinder radius="${caster_radius}" length="${caster_thickness}"/>
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${caster_radius}" length="${caster_thickness}"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference="caster_link">
            <material>Gazebo/Red</material>
        </gazebo> 
    </xacro:macro>
</robot>
