TrajectoryPlannerROS:
  max_vel_x: 2.5 # 5.6 mph
  min_vel_x: 0.1
  max_rotational_vel: 5.0
  min_in_place_rotational_vel: 5.0

  acc_lim_th: 2.5
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  xy_goal_tolerance:  0.25
  yaw_goal_tolerance: 0.50 
  holonomic_robot: false
