TrajectoryPlannerROS:
  max_vel_x: 2.0
  min_vel_x: 0.6
  max_rotational_vel: 2.0
  min_in_place_rotational_vel: 1

  acc_lim_th: 2
  acc_lim_x: 1
  acc_lim_y: .5

  yaw_goal_tolerance: 0.5 
  xy_goal_tolerance: 0.5
  latch_xy_goal_tolerance: true
  holonomic_robot: false
  
