# It's not possible to use the robot_radius parameter because Navi does not
# turn about its center.
footprint:
- [  0.178,  0.49 ] # front left
- [ -0.815,  0.49 ] # back left
- [ -0.815, -0.49 ] # back right
- [  0.178, -0.49 ] # front right

transform_tolerance: 0.5
max_obstacle_height: 1.5
obstacle_range: 4.0
raytrace_range: 4.0

# Configure the map to use voxels. It would be better to use a 2D costmap, but
# height is necessary to differentiate between physical obstacles and detected
# lines. Otherwise, the two clearing operations would interfere.
map_type: costmap
#map_type: voxel
#z_resolution: 0.3
#z_voxels: 5
track_unknown_space: true

observation_sources: laser detected_lines
laser: {
    topic: /laser,
    sensor_frame: /laser,
    data_type: LaserScan,
    obstacle_range: 4.0,
    raytrace_range: 4.0,
    marking: true,
    clearing: true
}
detected_lines: {
    topic: /vision/lines,
    sensor_frame: /base_footprint,
    data_type: PointCloud2,
    marking: true,
    clearing: true
}
