obstacle_range: 3
raytrace_range: 3
#add in real footprint sizes
# where should the foot print be centered?  
# is the use of the inflation radius valid here?
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.8
inflation_radius: 0.8
transform_tolerance: 5.0

observation_sources: laser_scan_sensor 
#stereo_objects

laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: base_laser/scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
