DWAPlannerROS:
  # Velocity Constraints
  max_trans_vel: 0.5 # m/s
  min_trans_vel: 0.2 # m/s
  max_rot_vel: 1.000 # rad/s
  min_rot_vel: 0.400 # rad/s
  max_vel_x: 0.5 # m/s
  min_vel_x: 0.2 # m/s
  max_vel_y: 0.0
  min_vel_y: 0.0

  # Acceleration Limits
  acc_lim_x:  4.0 # m/s^2
  acc_lim_y:  0.0 # m/s^2
  acc_lim_th: 16.0 # rad/s^2

  # Goal Tolerance
  xy_goal_tolerance:  0.25  # m
  yaw_goal_tolerance: 6.283 # rad

  # Velocity Sampling
  sim_time: 4.0
  vx_samples: 5
  vy_samples: 0
  vtheta_samples: 15
  penalize_negative_x: false
  controller_frequency: 20.0

  # Visualization
  prune_plan: false
