local_costmap:
  # Coordiante frames. We use /odom instead of /map (or /map_offset) because it
  # is guaranteed to be smooth over short period of time.
  global_frame: /odom
  robot_base_frame: /base_footprint
  rolling_window: true
  static_map: false

  # FIXME: Disable this to improve performance.
  publish_voxel_map: true

  # The local costmap is too big to publish for visualization.
  update_frequency: 20.0
  publish_frequency: 10.0

  resolution: 0.05
  width: 20.0
  height: 20.0
