port: /dev/ttyUSB0
name: motor_driver
publish: #list of published topics
 encoder: #topic name
  type: navi_driver/Encoder  #msg type
 current:
  type: navi_driver/Current
subscribe:
 cmd:
  type: navi_driver/MotorCmd
