local_costmap:
  global_frame: odom
  robot_base_frame: drive_center
  update_frequency: 10.0
  publish_frequency: 2.0
  static_map: true
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.05
